[package]
name = "advent_of_code_2020"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day_13_part_1_bus"
path = "day_13_part_1_bus.rs"

[[bin]]
name = "day_13_part_2_bus"
path = "day_13_part_2_bus.rs"

[dependencies]
